# - load itinerary from csv -
observeEvent(input$load, {
        rv$Tr <- NULL
        inFile <- input$load
        # validate(need(!is.null(inFile), "No correct csv file was selected"))
        if(is.null(inFile)){
                rv$infoText <- "No correct csv file was selected. Old itinerary was kept."
                return()
        }
        
        InTa <- read.csv(file = inFile$datapath, header = TRUE, sep = ";")
        # validate(need(ncol(InTable) == 5, "No correct csv file was selected"))
        if(!(ncol(InTa) %in% c(9))){
                rv$infoText <- "Loaded csv had not 5, 6, 7, or 8 columns. Old itinerary was kept."
                return()
        }
        
        Headers <- c("Name", "Category", "Start", "End", "Duration", "Link", "Comment", "estCost", "Rate")
        
        if(any(!(Headers %in% colnames(InTa)))) {
                rv$infoText <- "Could not assign all columns, file was probably not generated by this app"
                return()
        }
        
        colnames(InTa) <- Headers
        
        
        Costs <- suppressWarnings(as.numeric(InTa$estCost))
        
        InTa <- data.frame(lapply(InTa, as.character), stringsAsFactors=FALSE)
        
        InTa$estCost <- Costs
        
        if(any(is.na(lubridate::parse_date_time(InTa$Start, orders = "ymd HMS", tz = "CET")))){
                rv$infoText <- "Could not parse all Start times in loaded itinerary. Old itinerary was kept."
                return()
        }
        
        if(any(is.na(lubridate::parse_date_time(InTa$End, orders = "ymd HMS", tz = "CET")))){
                rv$infoText <- "Could not parse all End times in loaded itinerary. Old itinerary was kept."
                return()
        }
        
        InTa$Start <- lubridate::parse_date_time(InTa$Start, orders = "ymd HMS", tz = "CET")
        
        InTa$End <- lubridate::parse_date_time(InTa$End, orders = "ymd HMS", tz = "CET")
        
        
        # change the link format to real links
        InTa$Link[grep(pattern = ".",InTa$Link)] <- paste0("<a href='",InTa$Link[grep(pattern = ".",InTa$Link)],"' target='_blank'>",InTa$Name[grep(pattern = ".",InTa$Link)],"</a>")
        # InTa$Link <- tags$a(href = InTa$Link, target = InTa$Name)
        
        # make sure all Rates are appropriate
        InTa$Rate[!(InTa$Rate %in% c("","*", "**", "***", "****", "*****"))] <- ""
        
        # make sure all Categories are appropriate
        InTa$Category[!(InTa$Category %in% c("Transport", "Hotel", "Activity", "Food"))] <- "Activity"
        
        #rm(Times, Dates)
        rv$DFi <- InTa
        rv$infoText <- "Uploaded csv file with itinerary"
        
        # Attempt to set the Name when loading file
        NameGuess <- strsplit(inFile$name, split = "_")
        NameGuess <- strsplit(NameGuess[[length(NameGuess)]], split = ".csv")
        
        updateTextInput(session, inputId = "itname",
                        value = as.character(NameGuess[[length(NameGuess)]])
        )
        
})
# --